main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
main_add:
    path:     /add
    defaults: { _controller: MainBundle:Default:add }
main_edit:
    path:     /edit/{id}
    defaults: { _controller: MainBundle:Default:edit }
    requirements:
            id: \d+
main_delete:
    path:     /delete/{id}
    defaults: { _controller: MainBundle:Default:delete }
    requirements:
            id: \d+
main_detail:
    path:     /detail/{id}
    defaults: { _controller: MainBundle:Default:detail }
    requirements:
            id: \d+

